
FROM pytorch/pytorch

RUN pip3 install --no-cache-dir \
        pandas \
        scikit-learn==1.2.2 \
        mne \
        einops \
        jupyter \
        opencv-python
COPY notebooks ./notebooks
